panther_documents/authapp/urls.py
from django.urls import path

from authapp.views import ShopUserRegisterView, ShopUserLoginView, office, ShopUserLogoutView, VerifyView

app_name = 'auth'

urlpatterns = [
    # path('', office, name='office'),
    # path('register/', ShopUserRegisterView.as_view(), name='register'),
    # path('verify/', VerifyView.as_view(), name='wait_verify'),
    path('verify/<str:email>/<str:activation_key>/', VerifyView.as_view(), name='verify'),
    # path('login/', ShopUserLoginView.as_view(), name='login'),
    # path('logout/', ShopUserLogoutView.as_view(), name='logout')
]

panther_documents/mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import PassportListView, SupportView, page_not_found, get_products

app_name = 'main'

urlpatterns = [
    # path('', cache_page(60*60)(PassportListView.as_view()), name='home'),
    path('', PassportListView.as_view(), name='home'),
    path('get-products/', get_products, name='get-products'),
    path('support/', cache_page(60*60)(SupportView.as_view()), name='support')
]

# Works only when DEBUG = False
handler404 = page_not_found

panther_documents/panther_documents/urls.py
from django.contrib import admin
from django.templatetags.static import static
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

# noinspection SpellCheckingInspection
urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('mainapp.urls', namespace='main')),
    path('', include('paymentapp.urls', namespace='payment')),
    path('office/', include('authapp.urls', namespace='auth')),

    path('favicon.ico', RedirectView.as_view(url=static("favicon.ico"))),

    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name="javascript-catalog"), # No cache

    path('currencies/', include('currencies.urls'))
]

panther_documents/paymentapp/urls.py
from django.urls import path

from .views import CartView, SendLinksFormView, DownloadLinksView, PlisioPaymentView, PlisioStatus, SuccessPayment

app_name = 'payment'

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('transactions/plisio/<str:email>/<int:transaction_id>/', PlisioPaymentView.as_view(), name='plisio'),
    path('transaction/plisio/status/', PlisioStatus.as_view(), name='plisio-callback'),
    path('success-payment/', SuccessPayment.as_view(), name='success-payment'),
    path('get-files/', SendLinksFormView.as_view(), name='send-links'),
    path('get-file/<str:email>/<str:security_code>/', DownloadLinksView.as_view(), name='download')
]

panther_documents/paymentapp/forms.py
from captcha.fields import ReCaptchaField
from django import forms
from django.core.exceptions import ValidationError
from django.db.models import QuerySet
from django.utils.translation import gettext_lazy as _

from mainapp.models import Passport, BaseProduct
from paymentapp.models import Transaction


class BuyProductForm(forms.Form):
    # Union queryset
    queryset: QuerySet[BaseProduct] = Passport.objects.exclude(passportfile__is_sold=True, passportfile__is_reserved=True)

    email = forms.EmailField(label=_('Email'))
    products = forms.JSONField(label=_('Choose products'))  # [{'type': str, 'id': int|str, 'count': int|str}]
    gateway = forms.ChoiceField(
        choices=Transaction.PaymentMethod.choices,
        label=_('Payment method')
    )

    def __init__(self, *, user_email=None, **kwargs):
        super().__init__(**kwargs)

        field = self.fields['products']
        field.widget = field.hidden_widget()

        self.fields['email'].widget.attrs.update({'autocomplete': 'on'})
        if user_email is not None:
            self.fields['email'].widget.attrs.update({'value': user_email, 'autocomplete': 'on'})

    def clean_products(self):
        products_data: list[dict] = self.cleaned_data['products']

        if not products_data:
            raise ValidationError('Should be products to buy', 'empty cart')

        for p in products_data:
            if not p:
                raise ValidationError('Empty product info', 'empty item')

            pk = p.get('id')
            if pk is None:
                raise ValidationError('Not valid id in product provided', 'wrong data')

            product_type = p.get('type')
            if product_type is None or product_type not in BaseProduct.ProductTypes:
                raise ValidationError('Not valid type in product provided', 'wrong data')

            count = p.get('count')
            if count is None:
                raise ValidationError('Not valid count in product provided', 'wrong data')

            try:
                product: BaseProduct = self.queryset.filter(type=product_type, pk=int(pk)).first()
            except:
                raise ValidationError('Not valid data provided')

            if product is None:
                raise ValidationError('No available products in the cart', 'wrong data')

            max_count = product.get_count()
            if max_count < int(count) or int(count) < 1:
                raise ValidationError(f'Not valid count of {product.title_en} (maximum is {max_count})', 'wrong data')

        return products_data


class SendLinksForm(forms.Form):
    email = forms.EmailField()
    captcha = ReCaptchaField()

    transactions: list[Transaction]

    def clean_email(self):
        email = self.cleaned_data['email']
        if not Transaction.objects.filter(email=email).exists():
            raise ValidationError(_('Email not found'), code='not found')

        self.transactions = list(t for t in Transaction.objects.filter(email=email).all() if t.check_if_sold())

        if len(self.transactions) == 0:
            raise ValidationError(_('Not paid'), code='not paid')

        return email

panther_documents/paymentapp/views.py
import json
import logging
from typing import Union

from currencies.utils import convert
from django.http import JsonResponse, HttpResponseNotFound, HttpResponseRedirect, HttpResponseBadRequest, HttpRequest, HttpResponse, \
	HttpResponseForbidden, FileResponse
from django.urls import reverse_lazy, reverse
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import FormView, TemplateView

from mainapp.models import BaseProduct
from paymentapp import plisio
from paymentapp.forms import BuyProductForm, SendLinksForm
from paymentapp.models import Transaction, ProductFile, in_2_hours, PlisioGateway
from paymentapp.utils import send_transaction_links


logger = logging.getLogger('gunicorn')


# Get -> cart page, post -> JsonResponse
class CartView(FormView):
	form_class = BuyProductForm
	template_name = 'payment/cart_page.html'

	json_params = {'ensure_ascii': False}

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		if self.request.user.is_authenticated:
			kwargs['user_email'] = self.request.user.email
		return kwargs

	def form_valid(self, form):
		""" Create transaction and return JsonResponse with url """
		t = self.create_transaction(self.request.user, form)

		if t is None:
			response = {
				'success': False,
				'clean_cart': False,
				'reload_cart': True,
				'errors': {'cart': [_("Can not create transaction. Try again or write to support.")]},
				'url': self.request.path
			}
			return JsonResponse(response, json_dumps_params=self.json_params)

		self.success_url = t.get_gateway_url()
		response = {
			'success': True,
			'clean_cart': True,
			'reload_cart': False,
			'url': self.success_url
		}
		return JsonResponse(response, json_dumps_params=self.json_params)

	def form_invalid(self, form):
		response = {
			'success': False,
			'errors': form.errors,
			'clean_cart': False,
			'reload_cart': False,
			'url': self.request.path
		}
		return JsonResponse(response, json_dumps_params=self.json_params)

	@staticmethod
	def create_transaction(user, form: BuyProductForm) -> Union[Transaction, None]:
		email, gateway, products = (
			form.cleaned_data['email'],
			form.cleaned_data['gateway'],
			form.cleaned_data['products']
		)

		logger.info(f'Creating transaction for {email} with {gateway} and products: {products}')

		t = Transaction(email=email, gateway=gateway, invoice_price=0)  # invoice_price - for t.save()
		if user.is_authenticated:
			t.user_id = user.id

		reserved: list[tuple[BaseProduct, int]] = []

		try:
			for product in products:
				p: BaseProduct = BaseProduct.get_subclass(product['type']).objects.get(pk=product['id'])
				if not p.reserve(product['count']):  # Резервация товаров
					raise ValueError("Can not reserve")  # Резервация не удалась

				reserved.append((p, product['count']))
		except Exception as e:
			logger.error(str(e))
			for product, count in reserved:
				if not product.cancel_reserve(count):
					logger.warning(f'Failed to cancel reserve for product: {product.type} - {product.id}')

			return None

		t.save()  # Иначе нельзя ProductFile.create_from_base

		for product, count in reserved:
			# Раз нам пофиг кому какие достанутся - будем продавать любые зарезервированные
			for _ in range(count):
				ProductFile.create_from_base(product, t)

			# Считаем итоговую стоимость
			t.invoice_price += convert(product.price, product.currency, t.invoice_currency)

		t.save()

		return t


# Вьюшка для переадресации или вывода ошибки plisio
class PlisioPaymentView(View):
	def get(self, request, *args, **kwargs):
		t_id = kwargs.get('transaction_id')
		t_email = kwargs.get('email')

		if t_id is None:
			return HttpResponseNotFound()

		t: Transaction = Transaction.objects.filter(id=t_id, email=t_email).first()
		if t is None:
			return HttpResponseNotFound()

		if t.gateway != t.PaymentMethod.PLISIO:
			return HttpResponseNotFound()

		if t.check_if_sold():
			return HttpResponseRedirect(reverse_lazy('payment:success-payment'))

		p = self.create_invoice(t)
		if p is None:
			# Произошла ошибка платежного шлюза, попробуйте снова
			return HttpResponseBadRequest()

		t.plisio = p
		t.save()

		return HttpResponseRedirect(p.get_invoice_url())

	@staticmethod
	def create_invoice(transaction: Transaction) -> PlisioGateway | None:
		if transaction.plisio is not None:
			return transaction.plisio

		try:
			response = plisio.create_invoice(
				order_name=f'Transaction-{transaction.id}',
				order_number=str(transaction.id),
				source_amount=str(transaction.invoice_price),
				source_currency=transaction.invoice_currency,
				callback_url=str(reverse('payment:plisio-callback')),
				success_callback_url=str(reverse('payment:plisio-callback')),
				fail_callback_url=str(reverse('payment:plisio-callback')),
				email=transaction.email,
				expire_min=str((in_2_hours() - now()).seconds)
			)
		except plisio.PlisioException as e:
			logger.error(str(e))
			return None

		if response.get('status') == 'success':
			if (data := response.get('data')) is None:
				return None

			if data.get('txn_id') is None or data.get('invoice_url') is None:
				return None

			p = PlisioGateway(txn_id=data.get('txn_id'))
			p.update_fields(data)

			return p

		return None


# Вьюшка для получения статуса транзакции plisio
class PlisioStatus(View):
	# noinspection PyMethodMayBeStatic
	def post(self, request: HttpRequest, *args, **kwargs):
		response: dict = json.loads(request.body)
		if not plisio.verify_hash(response):
			return HttpResponseBadRequest()

		p: PlisioGateway = PlisioGateway.objects.filter(txn_id=response.get('txn_id')).first()
		if p is None:
			return HttpResponseBadRequest()

		if p.handle_callback(response):
			t = p.transaction
			if t.check_if_sold():
				send_transaction_links(t.email, [t], request.get_host(), request.scheme)

			return HttpResponse('ok')

		return HttpResponseBadRequest()


class SuccessPayment(TemplateView):
	template_name = 'payment/success_payment.html'


# Вьюшка для отправки ссылок на скачивание купленных товаров
class SendLinksFormView(FormView):
	form_class = SendLinksForm
	template_name = 'payment/send_links.html'
	success_url = reverse_lazy('main:home')

	def form_valid(self, form):
		domain = self.request.get_host()
		email = form.cleaned_data['email']

		if not send_transaction_links(email, form.transactions, domain, self.request.scheme):
			return self.form_invalid(form)

		return super().form_valid(form)


# Вьюшка для скачивания товаров
class DownloadLinksView(View):
	def get(self, request, *args, **kwargs):
		email = self.kwargs.get('email')
		security_code = self.kwargs.get('security_code')

		if email is None or security_code is None:
			return HttpResponseNotFound()

		try:
			product_info = ProductFile.objects.get(transaction__email=email, security_code=security_code)
		except ProductFile.DoesNotExist:
			return HttpResponseForbidden()

		return FileResponse(open(product_info.product_file.path, 'rb'))

panther_documents/paymentapp/templates/payment/cart_page.html
{% extends 'site_page.html' %}
{% load static i18n currency %}

{% block additional_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'payments/css/cart_page.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/popup.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'libs/fontawesome/css/fontawesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'libs/fontawesome/css/duotone.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'libs/fontawesome/css/solid.css' %}">
{% endblock %}


{% block additional_scripts %}
    <!-- Translation in js -->
    <script src="{% url 'javascript-catalog' %}"></script>
    <script src="{% static 'payments/js/cart_list.js' %}"></script>
    <script src="{% static 'payments/js/cart_buying_popup.js' %}"></script>
{% endblock %}


{% block main %}
    <form id="get-products-form" action="{% url 'main:get-products' %}" method="post" style="display: none">
        {% csrf_token %}
    </form>
    <div class="container">
        <div class="empty_cart inactive">
            <h3>{% trans 'You have not added any products to the cart' %}</h3>
        </div>
    </div>
    {% currency_context %}
    <div class="container">
        <div class="cart_page_wrap inactive">
            <h3 class="cart_page_header">{% trans 'Cart' %}</h3>
            <div class="product_list"></div>
            <div class="final_price_div">
                <span>
                    {% trans 'Total' %}:
                    <!--suppress HtmlUnknownAttribute -->
                    <span id="final_price" currency-factor="{{ CURRENCY.factor }}">0</span>
                    <span class="currency-symbol">{{ CURRENCY.symbol }}</span>
                </span>
            </div>
            <div class="pay_btn_div">
                <button class="cart_pay_btn">{% trans 'Select payment method' %}</button>
            </div>
        </div>
    </div>
{% endblock %}


{% block popup %}
    <div class="popup">
        <div class="popup_content">
            <div class="popup_header" style="justify-content: space-between;">
                <h3>{% trans 'Enter email' %}</h3>
                <i class="fa-duotone fa-xmark fa-xl popup_close"></i>
            </div>

            <form method="dialog" onsubmit="send_pay_form(this)" action="{% url 'payment:cart' %}"
                  class="popup_form" id="pay_form">
                <div class="form_content">
                    <div class="alert">
                        <ul>
                            <!-- TODO errors -->
                        </ul>
                    </div>

                    {% csrf_token %}
                    {{ form.as_div }}

                    <div class="form_content_btns" style="margin-bottom: 10px;">
                        <button type="submit" class="pay_btn">{% trans 'Pay' %}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

panther_documents/paymentapp/templates/payment/send_links.html
{% extends 'site_page.html' %}
{% load static %}
{% load i18n %}

{% block additional_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'auth/css/auth.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'libs/fontawesome/css/fontawesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'libs/fontawesome/css/duotone.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'libs/fontawesome/css/solid.css' %}">
{% endblock %}


{% block main %}
    <div class="page_wrap">
        <div class="form_wrap">
            <div class="alert">
                <ul>
                    {% for field in form %}
                        {% if field.errors %}<li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
                    {% endfor %}
                </ul>
                {{form.non_field_errors}}
            </div>

            <h3>{% trans 'Enter the email address to receive the files.' %}</h3>
            <form method="post" class="form_inside">
                {% for field in form %}
                    {{field}}
                {% endfor %}
                {% csrf_token %}
                <button type="submit" id="input_submit">{% trans 'Send links' %}</button>
            </form>
        </div>
    </div>
{% endblock %}

panther_documents/paymentapp/templates/payment/success_payment.html
{% extends 'base.html' %}

{% block main %}
	<h2>Thanks for buying!</h2>
    <h3>
        If you are not received mail with links to files - go to
        <a href="{% url 'payment:send-links' %}">this</a> page.
    </h3>
{% endblock %}