panther_documents/authapp/urls.py
from django.urls import path

from authapp.views import ShopUserRegisterView, ShopUserLoginView, office, ShopUserLogoutView, VerifyView

app_name = 'auth'

urlpatterns = [
    # path('', office, name='office'),
    # path('register/', ShopUserRegisterView.as_view(), name='register'),
    # path('verify/', VerifyView.as_view(), name='wait_verify'),
    path('verify/<str:email>/<str:activation_key>/', VerifyView.as_view(), name='verify'),
    # path('login/', ShopUserLoginView.as_view(), name='login'),
    # path('logout/', ShopUserLogoutView.as_view(), name='logout')
]

panther_documents/mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import PassportListView, SupportView, page_not_found, get_products

app_name = 'main'

urlpatterns = [
    # path('', cache_page(60*60)(PassportListView.as_view()), name='home'),
    path('', PassportListView.as_view(), name='home'),
    path('get-products/', get_products, name='get-products'),
    path('support/', cache_page(60*60)(SupportView.as_view()), name='support')
]

# Works only when DEBUG = False
handler404 = page_not_found

panther_documents/panther_documents/urls.py
from django.contrib import admin
from django.templatetags.static import static
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

# noinspection SpellCheckingInspection
urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('mainapp.urls', namespace='main')),
    path('', include('paymentapp.urls', namespace='payment')),
    path('office/', include('authapp.urls', namespace='auth')),

    path('favicon.ico', RedirectView.as_view(url=static("favicon.ico"))),

    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name="javascript-catalog"), # No cache

    path('currencies/', include('currencies.urls'))
]

panther_documents/paymentapp/urls.py
from django.urls import path

from .views import CartView, SendLinksFormView, DownloadLinksView, PlisioPaymentView, PlisioStatus, SuccessPayment

app_name = 'payment'

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('transactions/plisio/<str:email>/<int:transaction_id>/', PlisioPaymentView.as_view(), name='plisio'),
    path('transaction/plisio/status/', PlisioStatus.as_view(), name='plisio-callback'),
    path('success-payment/', SuccessPayment.as_view(), name='success-payment'),
    path('get-files/', SendLinksFormView.as_view(), name='send-links'),
    path('get-file/<str:email>/<str:security_code>/', DownloadLinksView.as_view(), name='download')
]

panther_documents/templates/components/burger2close.html
<div class="burger">
    <div class="inner">
        <span class="line"></span>
        <span class="line"></span>
        <span class="line"></span>
    </div>
</div>

panther_documents/templates/components/currency_switch.html
{% load currency %}
{% currency_context %}

<div class="curr-select" id="currency-select">
    <form action="{% url 'currencies_set_currency' %}" method="post">
        {% csrf_token %}
        <input id="curr-picker" name="currency_code" type="hidden" value="{{ CURRENCY_CODE }}">
    </form>

    <div class="curr-selected"><span>{{ CURRENCY.code }}</span></div>
    <div class="options-container">
        {% for currency in CURRENCIES %}
            <div class="option">
                <label for="curr_{{ currency.code }}">{{ currency.code }}</label>
                <input type="radio" id="curr_{{ currency.code }}" value="{{ currency.code }}">
            </div>
        {% endfor %}
    </div>
</div>

panther_documents/templates/components/footer.html
<div class="container">
    <div class="footer_wrap">
        <span>PantherDoc 2023</span>
    </div>
</div>

panther_documents/templates/components/header.html
{% load i18n %}

<div class="container">
    <nav class="menu">
        <div class="header_title">
            <a href="{% url 'main:home' %}"><h2>PantherDoc</h2></a>
        </div>
        <div class="header_content">
{#            {% if not user.is_authenticated %}#}
{#                <a class="not-mobile" href="{% url 'auth:login' %}">{% trans 'Sign in' %}</a>#}
{#                <a class="not-mobile" href="{% url 'auth:register' %}">{% trans 'Sign up' %}</a>#}
{#            {% else %}#}
{#                <a class="not-mobile" href="{% url 'auth:office' %}">{% trans 'Office' %}</a>#}
{#            {% endif %}#}

            <a href="{% url 'payment:cart' %}" class="header_cart">
                <i class="fa-duotone fa-cart-shopping"></i>
                <span class="cart_counter" id="cart-counter">0</span>
            </a>

            <div class="burger_menu" id="menu-control">
                {% include 'components/burger2close.html' %}
            </div>
        </div>
    </nav>
    <nav class="hide_element_mobile header_menu" id="header-menu">
{#        {% if not user.is_authenticated %}#}
{#            <a class="mobile" href="{% url 'auth:login' %}">{% trans 'Sign in' %}</a>#}
{#            <a class="mobile" href="{% url 'auth:register' %}">{% trans 'Sign up' %}</a>#}
{#        {% else %}#}
{#            <a class="mobile" href="{% url 'auth:office' %}">{% trans 'Office' %}</a>#}
{#        {% endif %}#}

        <a href="{% url 'payment:send-links' %}">{% trans 'My purchases' %}</a>
        <a href="{% url 'main:support' %}">{% trans 'Support' %}</a>
    </nav>
    <div class="pickers">
        <div class="currency-picker">
            {% include 'components/currency_switch.html' %}
        </div>
        <div class="lang-picker">
            {% include 'components/lang_switch.html' %}
        </div>
    </div>
</div>

panther_documents/templates/components/lang_switch.html
{% load i18n %}

<div class="lang-select" id="lang-select">
    {% get_current_language as LANGUAGE_CODE %}
    {% get_language_info for LANGUAGE_CODE as cur_lang %}

    {% get_available_languages as LANGUAGES %}
    {% get_language_info_list for LANGUAGES as languages %}

    <form action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
        <input id="lang-picker" name="language" type="hidden" value="{{ LANG_CODE }}">
    </form>

    <div class="lang-selected"><span>{{ cur_lang.name_local }}</span></div>
    <div class="options-container">
        {% for lang in languages %}
            <div class="option">
                <label for="lang_{{ lang.code }}">{{ lang.name_local }}</label>
                <input type="radio" id="lang_{{ lang.code }}" value="{{ lang.code }}">
            </div>
        {% endfor %}
    </div>
</div>

<div id="current-language" style="display: none">{{ LANGUAGE_CODE }}</div>